services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Rfuehricht\Recordmodules\:
    resource: '../Classes/*'
    autowire: true
    public: true

  Rfuehricht\Recordmodules\Event\BeforePidsLoadedEvent:
    autowire: false

  Rfuehricht\Recordmodules\Event\AfterPidsLoadedEvent:
    autowire: false
